### PR TITLE
WIP: Use TuyaClient instead of polling

### PR DESCRIPTION
**Pull request by emontnemery**
Changes in tuyamqtt for `TuyaClient` added in TradeFace/tuya#31
By using `TuyaClient` instead of polling, status updates are instant.

WIP:
- Depends on TradeFace/tuya#32
- Should poll for status when TuyaClient (re)connects to device
- Maybe make it optional to use `TuyaClient`, according to this comment some devices won't maintain a connection: https://github.com/TradeFace/tuya/issues/29#issuecomment-630438619

Also, there is a threading bug in `TuyaMQTTEntity` which is accidentally solved / hidden by this PR:
`TuyaMQTTEntity` periodically polls for status, and there may be an incoming MQTT message while this is in progress. There should be a lock or other method in `TuyaMQTTEntity` to serialize accesses to the Tuya device.

### CODE REVIEW

**Comment by TradeFace** [comment]
Merged the into https://github.com/TradeFace/tuyamqtt/tree/feature/tuyaface

**Comment by TradeFace** [comment]
@emontnemery  When I have 2 instances of tuyamqtt running stuff spins out of control. 

```
TuyaClient: exception when reading from socket
TuyaClient: reconnecting
TuyaClient: exception when reading from socket
TuyaClient: reconnecting
.... x 30/sec
```

**Comment by emontnemery** [comment]
@TradeFace Most/all Tuya devices only support one connection, so this is expected.

**Comment by emontnemery** [comment]
If there's a valid use case for multiple instances of tuyamqtt, maybe it should be an option in tuyamqtt to use TuyaClient to keep the connection open and get instant status changes from the devices, or to do polling?

**Comment by TradeFace** [comment]
Yeah it is expected to a certain degree. But it could be throttled down perhaps. I am not using the Smart Live app myself, but many people do. That would presumably trigger the same kind of rapid fight over device access. Which could lead to heavy network traffic and general performance degradation.

**Comment by emontnemery** [comment]
OK, that's a good point.
TuyaClient could back of the connect attempts exponentially until reaching some maximum retry value.

What do you think is reasonable? Maybe every 30s or so?

**Comment by TradeFace** [comment]
throttling back 30s should be okay, maybe even shorter.

**Pull request closed without merging**
